dist: xenial

# TODO: use Nix as the language to manage system packages in one
# place. Currently building with Nix fails with error 'no space left
# on device'.
language: minimal

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
      - zlibc
      - llvm

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-nix --no-terminal --install-ghc test --only-dependencies

script:
# Build the package, its tests, and its docs and run the tests
- stack --no-nix --no-terminal test --haddock --no-haddock-deps
