name:                ray-tracer
version:             0.1.0.0
license:             GPL-3

dependencies:
- base >= 4.7 && < 5
- GlomeVec
- hip
- random
- array

default-extensions:
- DataKinds
- KindSignatures
- OverloadedLists
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TypeApplications
- ViewPatterns
- TupleSections

library:
  source-dirs: src
