name:                ray-tracer
version:             0.1.0.0
license:             GPL-3

dependencies:
- base >= 4.7 && < 5
- GlomeVec
- hip
- random
- array
- mwc-random
- mtl

default-extensions:
- DataKinds
- KindSignatures
- OverloadedLists
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TypeApplications
- ViewPatterns
- TupleSections
- GeneralizedNewtypeDeriving
- FlexibleContexts
- MultiParamTypeClasses
- LambdaCase

library:
  source-dirs: src

executables:
  raytracer:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - ray-tracer

tests:
  raytracer-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    dependencies:
    - ray-tracer

benchmarks:
  raytracer-benchmark:
    source-dirs: benchmark
    main: Benchmark.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - ray-tracer
    - time
    - process
